name: servicos
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Animations
  animations: ^2.0.11

  # Firebase
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_messaging: ^15.1.3
  firebase_performance: ^0.10.0+4
  firebase_storage: ^12.3.4

# Google Maps
  google_maps_flutter: ^2.9.0

# HTTP  
  http: ^1.2.2

# Image Picker
  image_picker: ^1.1.2

# Url Launcher
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
